# Generated by Django 4.1.3 on 2022-11-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0002_course_image"),
        ("users", "0002_student"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="Enrolment",
        ),
    ]
