[tool.poetry]
name = "site"
version = "1.0.0"
description = "The project responsible for maintaining our website and all of its subdomains."
authors = ["Python Discord <info@pythondiscord.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.*"
django = "4.1.5"
django-environ = "0.9.0"
django-filter = "22.1"
djangorestframework = "3.14.0"
psycopg2-binary = "2.9.5"
django-simple-bulma = "2.5.0"
whitenoise = "6.3.0"
httpx = "0.23.3"
pyyaml = "6.0"
gunicorn = "20.1.0"
sentry-sdk = "1.14.0"
markdown = "3.4.1"
python-frontmatter = "1.0.0"
django-prometheus = "2.2.0"
django-distill = "3.0.2"
PyJWT = {version = "2.6.0", extras = ["crypto"]}
pymdown-extensions = "9.9.2"

[tool.poetry.dev-dependencies]
coverage = "7.1.0"
flake8 = "6.0.0"
flake8-annotations = "3.0.0"
flake8-bandit = "4.1.1"
flake8-bugbear = "23.1.20"
flake8-docstrings = "1.7.0"
flake8-import-order = "0.18.2"
flake8-tidy-imports = "4.8.0"
flake8-string-format = "0.3.0"
flake8-todo = "0.7"
pep8-naming = "0.13.3"
pre-commit = "3.0.2"
pyfakefs = "5.1.0"
taskipy = "1.10.3"
python-dotenv = "0.21.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
start = "python manage.py run --debug"
makemigrations = "python manage.py makemigrations"
django_shell = "python manage.py shell"
test = "coverage run manage.py test"
coverage = "coverage run manage.py test --no-input && coverage report -m"
report = "coverage report -m"
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
static = "python manage.py distill-local build --traceback --force"
