name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    name: Deploy to Kubernetes Cluster
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      # Check out the private Kubernetes repository for the
      # deployment.yaml file using a GitHub Personal Access
      # Token to get access.
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: python-discord/kubernetes

      - uses: azure/setup-kubectl@v3

      - name: Authenticate with Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v4
        with:
          manifests: |
              namespaces/default/site/deployment.yaml
          images: 'ghcr.io/python-discord/site:${{ steps.sha_tag.outputs.tag }}'

      - name: Purge Cloudflare Edge Cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: 989c984a358bfcd1e9b9d188cc86c1df
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_TOKEN }}
