name: Build & Publish Static Preview

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Static Preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Create a commit SHA-based tag for the container repositories
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the container, including an inline cache manifest to
      # allow us to use the registry as a cache source.
      - name: Build Docker Image (Main)
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/python-discord/static-site:latest
          cache-to: type=inline
          tags: |
            ghcr.io/python-discord/static-site:latest
            ghcr.io/python-discord/static-site:${{ steps.sha_tag.outputs.tag }}
          build-args: |
            git_sha=${{ github.sha }}
            STATIC_BUILD=TRUE

      - name: Extract Build From Docker Image (Main)
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir docker_build \
          && docker run --entrypoint /bin/echo --name site \
          ghcr.io/python-discord/static-site:${{ steps.sha_tag.outputs.tag }} \
          && docker cp site:/app docker_build/

      # Build directly to a local folder
      - name: Build Docker Image (PR)
        uses: docker/build-push-action@v4
        if: github.ref != 'refs/heads/main'
        with:
          context: .
          push: false
          cache-from: type=registry,ref=ghcr.io/python-discord/static-site:latest
          outputs: type=local,dest=docker_build/
          build-args: |
            git_sha=${{ github.sha }}
            STATIC_BUILD=TRUE

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: static-build
          path: docker_build/app/build/
          if-no-files-found: error
