version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    environment:
      - APP_NAME=flask-app
      - CAMERA_STREAM_URL=0
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"